const fs=require('fs'),vm=require('vm'),path=require('path');
const root=path.resolve(__dirname,'..');
const parser=new Function(fs.readFileSync(path.join(root,'extension/core/parser.js'),'utf8')+';return ZSParse;')();
let seed=0x5eed1234; const rnd=()=>((seed=(seed*1664525+1013904223)>>>0)/4294967296);
const chars='{}[],:"\\\n abcXYZ0123#<>|_-';
for(let i=0;i<5000;i++){let s='';const n=Math.floor(rnd()*500);for(let j=0;j<n;j++)s+=chars[Math.floor(rnd()*chars.length)];for(const fn of ['parseToolCalls','hasOpenToolBlock','hasToolSignature','hasCommandShape','isInjectedFeedback','toolNameFromText','salvageCutOff']){try{parser[fn](s)}catch(e){throw new Error(`${fn} crashed on fuzz case ${i}: ${e.message}`)}}}
for(let i=0;i<1000;i++){const payload={command:'tool_'+i,params:{text:`braces {${i}} quotes \\" nested`,items:[i,true,null,{x:'y'}]}};const out=parser.parseToolCalls(JSON.stringify(payload));if(out.length!==1||out[0].tool!==payload.command||out[0].arguments.items[0]!==i)throw new Error('roundtrip '+i)}
const providers=['arena','chatgpt','deepseek','gemini','glm','kimi','meta','notion','qwen'];
const required=['id','displayName','getEditor','typeAndSend','conversationKey','installSendHooks'];
for(const name of providers){const code=fs.readFileSync(path.join(root,'extension/providers',name+'.js'),'utf8');const storage=new Map();const localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,String(v)),removeItem:k=>storage.delete(k)};const nil=()=>null;const doc={querySelector:nil,querySelectorAll:()=>[],getElementById:nil,documentElement:{dataset:{},contains:()=>true},body:{contains:()=>true},addEventListener:()=>{}};function HTMLTextAreaElement(){};Object.defineProperty(HTMLTextAreaElement.prototype,'value',{get(){return this._v||''},set(v){this._v=v}});const c={console,document:doc,window:{localStorage,HTMLTextAreaElement},HTMLTextAreaElement,globalThis:null,localStorage,location:{href:'https://example.com/chat',pathname:'/chat',search:'',hash:'',hostname:'example.com'},MutationObserver:function(){this.observe=()=>{};this.disconnect=()=>{}},KeyboardEvent:function(){},Event:function(){},InputEvent:function(){},Node:{TEXT_NODE:3,ELEMENT_NODE:1},HTMLElement:function(){},CSS:{escape:x=>x},setTimeout,clearTimeout,setInterval:()=>0,clearInterval:()=>{},requestAnimationFrame:f=>0};c.globalThis=c;vm.createContext(c);try{vm.runInContext(code+';globalThis.__P=ZSProvider;',c,{timeout:1000})}catch(e){throw new Error(name+' load failed: '+e.message)}for(const key of required)if(c.__P[key]===undefined)throw new Error(name+' missing '+key);if(c.__P.id!==name)throw new Error(name+' id mismatch '+c.__P.id)}
console.log(`PASS extension stress: 5000 malformed parser cases, 1000 command roundtrips, ${providers.length} provider contracts`);
