const fs=require('fs'),vm=require('vm');
const code=fs.readFileSync('extension/providers/notion.js','utf8'),main=fs.readFileSync('extension/core/main.js','utf8');
for(const forbidden of ['tryPreferredModelRouting','modelSelectorControl','exactModelMatch','visible-picker+prompt','directModelPresets','BEHAVIOR CONTRACT','ANTI-COLLAPSE','role-play Claude Opus 5 if it is unavailable.\nBEHAVIOR'])if(code.includes(forbidden))throw new Error('forbidden direct/emulation content: '+forbidden);
const store=new Map(),localStorage={getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};
const c={console,window:{localStorage},localStorage,document:{documentElement:{dataset:{}},querySelectorAll:()=>[]},location:{pathname:'/chat',search:'',hash:'',href:'https://example.com/chat'},setTimeout,clearTimeout,MutationObserver:function(){this.observe=()=>{}},KeyboardEvent:function(){}};c.globalThis=c;vm.createContext(c);vm.runInContext(code+'\n;globalThis.__P=ZSProvider;',c);const P=c.__P;
for(const [id,model] of [['opus55','Claude Opus 5.5'],['opus','Claude Opus 5'],['kimi','Kimi K3'],['gpt','GPT-5.6 Sol']]){P.setAutoRoutingProfile(id);const d=P.routingProfileDiagnostics(),prompt=P.getStartupProfilePrompt();if(!d.promptReady||d.requestedModel!==model||!d.includesSharedSystem||!prompt.includes('Preferred model: '+model)||!prompt.includes('real '+model+' model')||!prompt.includes('Do not emulate or role-play'))throw new Error(id+' minimal routing request invalid');if(id==='opus55'&&(!prompt.includes("Notion Auto's best eligible model")||!prompt.includes('never claim it was selected unless Notion itself confirms that selection')))throw new Error('opus55 fallback is not honest');if(prompt.length>600)throw new Error(id+' routing request is no longer minimal');}
for(const x of ['providerProfile ? base.replace','const custom = [economy, quality, providerBehavior','Notion Auto preferred model','Check selection','complete shared Multi-Script skills'])if(!main.includes(x))throw new Error('placement/UI missing '+x);
P.setAutoRoutingProfile('');if(P.getStartupProfilePrompt()!=='')throw new Error('standard auto');
if(!P.routingProfileDiagnostics().directPickerInteraction===false)throw new Error('direct picker flag');
console.log('PASS prompt-only real-model requests followed by shared Multi-Script system');
