--!strict
-- Multi-Script Companion v6: diagnostic/readiness only.
-- Native execution remains exclusively on Roblox Studio's official live MCP server.
local HttpService=game:GetService("HttpService")
local Selection=game:GetService("Selection")
local RunService=game:GetService("RunService")
local ServerStorage=game:GetService("ServerStorage")
local ReplicatedStorage=game:GetService("ReplicatedStorage")
local TestService=game:GetService("TestService")
local PLUGIN_VERSION="6.13.0"
local DIAGNOSTIC_VERSION=2
local BRIDGE_URL="http://127.0.0.1:17614"
local POLL_SECONDS=5
local MAX_ISSUES=100
local SCAN_YIELD_EVERY=150
local toolbar=plugin:CreateToolbar("Multi-Script")
local toggle=toolbar:CreateButton("Multi-Script Companion","Show official MCP health and project readiness","rbxassetid://4458901886")
toggle.ClickableWhenViewportHidden=true
local widget=plugin:CreateDockWidgetPluginGui("MultiScriptCompanion_v6",DockWidgetPluginGuiInfo.new(Enum.InitialDockState.Right,false,false,420,620,340,420));widget.Title="Multi-Script Companion"
local root=Instance.new("ScrollingFrame");root.Size=UDim2.fromScale(1,1);root.BackgroundColor3=Color3.fromRGB(24,26,32);root.BorderSizePixel=0;root.ScrollBarThickness=6;root.AutomaticCanvasSize=Enum.AutomaticSize.Y;root.Parent=widget
local pad=Instance.new("UIPadding");pad.PaddingTop=UDim.new(0,12);pad.PaddingBottom=UDim.new(0,12);pad.PaddingLeft=UDim.new(0,12);pad.PaddingRight=UDim.new(0,12);pad.Parent=root
local list=Instance.new("UIListLayout");list.Padding=UDim.new(0,8);list.Parent=root
local function label(text:string,h:number,bold:boolean?):TextLabel local x=Instance.new("TextLabel");x.Size=UDim2.new(1,0,0,h);x.BackgroundTransparency=1;x.Text=text;x.TextColor3=Color3.fromRGB(226,230,240);x.TextSize=bold and 18 or 13;x.Font=bold and Enum.Font.GothamBold or Enum.Font.Gotham;x.TextWrapped=true;x.TextXAlignment=Enum.TextXAlignment.Left;x.TextYAlignment=Enum.TextYAlignment.Top;x.Parent=root;return x end
local function button(text:string):TextButton local x=Instance.new("TextButton");x.Size=UDim2.new(1,0,0,36);x.BackgroundColor3=Color3.fromRGB(52,91,196);x.Text=text;x.TextColor3=Color3.new(1,1,1);x.TextSize=13;x.Font=Enum.Font.GothamSemibold;x.Parent=root;local c=Instance.new("UICorner");c.CornerRadius=UDim.new(0,6);c.Parent=x;return x end
local function tint(x:TextLabel,state:string)x.TextColor3=state=="good" and Color3.fromRGB(101,214,143) or state=="warn" and Color3.fromRGB(244,190,80) or state=="bad" and Color3.fromRGB(245,112,120) or Color3.fromRGB(226,230,240) end
label("Multi-Script Companion",26,true)
local bridgeLabel=label("Bridge: checking…",38);local studioLabel=label("Studio MCP: checking…",52);local versionLabel=label("Compatibility: checking…",38);local readinessLabel=label("Readiness: scan not run",44);local projectLabel=label("Project inventory: waiting",52);local selectionLabel=label("Selection: none",34)
local refreshButton=button("Refresh live status");local scanButton=button("Run non-destructive readiness scan");local diagnosticButton=button("Print sanitized diagnostic report");local catalogButton=button("Print official native tool catalog");local prepareButton=button("Create optional Multi-Script folders")
local catalogLabel=label("Native catalog not loaded",42);local guidance=label("Diagnostic-only: no AI job polling, tool execution, source upload, secret handling, or fabricated Roblox commands. Real mutations use official Studio MCP tools.",70);guidance.TextColor3=Color3.fromRGB(166,176,200)
local alive=true;local busy=false;local lastStatus:any=nil;local lastScan={score=90,issueCount=0,high=0,medium=0,low=0,scanned=0,unreadable=0,durationMs=0}
local function inventory()local r={scripts=0,modules=0,remotes=0,animations=0,sounds=0,particles=0,screenGuis=0,descendants=0};for _,x in game:GetDescendants()do r.descendants+=1;if x:IsA("ModuleScript")then r.modules+=1 elseif x:IsA("LuaSourceContainer")then r.scripts+=1 elseif x:IsA("RemoteEvent")or x:IsA("RemoteFunction")then r.remotes+=1 elseif x:IsA("Animation")then r.animations+=1 elseif x:IsA("Sound")then r.sounds+=1 elseif x:IsA("ParticleEmitter")then r.particles+=1 elseif x:IsA("ScreenGui")then r.screenGuis+=1 end end;return r end
local function updateSelection()local s=Selection:Get();selectionLabel.Text=#s==0 and "Selection: none" or string.format("Selection: %d · first: %s (%s)",#s,string.sub(s[1]:GetFullName(),1,90),s[1].ClassName)end
local function heartbeat()local i=inventory();local body=HttpService:JSONEncode({pluginVersion=PLUGIN_VERSION,diagnosticVersion=DIAGNOSTIC_VERSION,placeId=game.PlaceId,placeName=string.sub(game.Name,1,120),isRunning=RunService:IsRunning(),selectionCount=#Selection:Get(),scriptCount=i.scripts,moduleCount=i.modules,readinessScore=lastScan.score,issueCount=lastScan.issueCount,highIssueCount=lastScan.high,scanDurationMs=lastScan.durationMs});pcall(function()HttpService:RequestAsync({Url=BRIDGE_URL.."/plugin/heartbeat",Method="POST",Headers={["Content-Type"]="application/json"},Body=body})end)end
local function refresh()if busy then return end;busy=true;local ok,res=pcall(function()return HttpService:RequestAsync({Url=BRIDGE_URL.."/status",Method="GET",Headers={["Accept"]="application/json"}})end);if ok and res.Success then local decoded,data=pcall(function()return HttpService:JSONDecode(res.Body)end);if decoded and type(data)=="table"then lastStatus=data;local r=data.roblox or {};local bv=tostring(data.bridgeVersion or "?");bridgeLabel.Text="Bridge: online · v"..bv.." · loopback only";tint(bridgeLabel,"good");versionLabel.Text=bv==PLUGIN_VERSION and "Compatibility: plugin and bridge versions match" or string.format("Compatibility: plugin v%s / bridge v%s · update older component",PLUGIN_VERSION,bv);tint(versionLabel,bv==PLUGIN_VERSION and "good" or "warn");if r.connected then studioLabel.Text=string.format("Studio MCP: loaded place connected · %d official native tools",tonumber(r.nativeTools)or 0);tint(studioLabel,"good")elseif r.alive then studioLabel.Text="Studio MCP proxy alive, but no usable place is connected";tint(studioLabel,"warn")else studioLabel.Text="Studio MCP offline · start bridge and enable Studio as MCP Server";tint(studioLabel,"bad")end;heartbeat()else bridgeLabel.Text="Bridge: invalid local response";tint(bridgeLabel,"bad")end else bridgeLabel.Text="Bridge offline, or Studio HTTP Requests are disabled";studioLabel.Text="Enable Game Settings → Security → Allow HTTP Requests";tint(bridgeLabel,"bad");tint(studioLabel,"warn")end;updateSelection();busy=false end
local RISKS={{"loadstring","dynamic loadstring execution","high"},{"require%s*%(%s*%d+","numeric asset require; verify supply chain","high"},{"OnServerInvoke","RemoteFunction handler; validate input, timeout, and failure","medium"},{"OnServerEvent","RemoteEvent handler; validate authority and rate limits","medium"},{"GetAsync%s*%(","GetAsync; verify pcall, budgets and retry","medium"},{"SetAsync%s*%(","SetAsync; prefer UpdateAsync for contested data","medium"},{"while%s+true%s+do","unbounded loop; verify yield and cancellation","medium"},{"WaitForChild%s*%([^,%)]*%)","WaitForChild without timeout","low"},{"task%.spawn%s*%(","spawned task; verify ownership and cancellation","low"}}
local function scan()if busy then return end;busy=true;scanButton.Text="Scanning…";local started=os.clock();local issues={};local c={high=0,medium=0,low=0};local scanned=0;local unreadable=0;local visited=0;for _,x in game:GetDescendants()do visited+=1;if x:IsA("LuaSourceContainer")then scanned+=1;local ok,src=pcall(function()return x.Source end);if ok then for _,r in RISKS do if string.find(src,r[1])then c[r[3]]+=1;table.insert(issues,string.format("[%s] %s — %s",string.upper(r[3]),x:GetFullName(),r[2]));if #issues>=MAX_ISSUES then break end end end else unreadable+=1 end end;if #issues>=MAX_ISSUES then break end;if visited%SCAN_YIELD_EVERY==0 then task.wait()end end;local ms=math.floor((os.clock()-started)*1000+.5);local score=math.max(0,100-c.high*12-c.medium*4-c.low-unreadable*2);lastScan={score=score,issueCount=#issues,high=c.high,medium=c.medium,low=c.low,scanned=scanned,unreadable=unreadable,durationMs=ms};readinessLabel.Text=string.format("Readiness: %d/100 · %d high · %d medium · %d low",score,c.high,c.medium,c.low);tint(readinessLabel,c.high>0 and "bad" or c.medium>0 and "warn" or "good");projectLabel.Text=string.format("Project scan: %d scripts · %d unreadable · %d ms · capped at %d findings",scanned,unreadable,ms,MAX_ISSUES);if #issues>0 then warn("[Multi-Script] Heuristic readiness findings (review context; not proof of a bug):\n- "..table.concat(issues,"\n- "))end;scanButton.Text="Run non-destructive readiness scan";busy=false;heartbeat()end
local function catalog()local ok,res=pcall(function()return HttpService:RequestAsync({Url=BRIDGE_URL.."/catalog",Method="GET",Headers={["Accept"]="application/json"}})end);if not ok or not res.Success then catalogLabel.Text="Catalog unavailable";return end;local decoded,d=pcall(function()return HttpService:JSONDecode(res.Body)end);if not decoded then return end;local tools=d.tools or {};catalogLabel.Text=string.format("Official native: %d · Multi-Script: %d direct + %d virtual Roblox + %d Roblox skills",#tools,tonumber(d.multiScriptDirectTools)or 0,tonumber(d.robloxVirtualTools)or 0,tonumber(d.robloxSkills)or 0);local n={};for _,t in tools do table.insert(n,tostring(t.name or "?"))end;print("[Multi-Script] Official Roblox Studio MCP catalog (controlled by Roblox):\n- "..table.concat(n,"\n- "))end
local function diagnostic()local i=inventory();local r=lastStatus and lastStatus.roblox or {};print("[Multi-Script] Sanitized diagnostic report:\n"..HttpService:JSONEncode({pluginVersion=PLUGIN_VERSION,diagnosticVersion=DIAGNOSTIC_VERSION,bridgeVersion=lastStatus and lastStatus.bridgeVersion or nil,studioMcpConnected=r.connected==true,officialNativeToolCount=r.nativeTools or 0,placeId=game.PlaceId,placeName=string.sub(game.Name,1,120),isRunning=RunService:IsRunning(),selectionCount=#Selection:Get(),inventory=i,readiness=lastScan,privacy="No source, secrets, assets, prompts, or AI jobs included."}))end
local function folder(parent:Instance,name:string)local x=parent:FindFirstChild(name);if x and x:IsA("Folder")then return end;local f=Instance.new("Folder");f.Name=name;f:SetAttribute("MultiScriptManaged",true);f.Parent=parent end
local function prepare()folder(ServerStorage,"MultiScript");folder(ReplicatedStorage,"MultiScript");folder(TestService,"MultiScriptTests");projectLabel.Text="Optional workspace ready · only missing folders created";heartbeat()end
toggle.Click:Connect(function()widget.Enabled=not widget.Enabled;if widget.Enabled then task.spawn(refresh)end end);refreshButton.Activated:Connect(function()task.spawn(refresh)end);scanButton.Activated:Connect(function()task.spawn(scan)end);diagnosticButton.Activated:Connect(diagnostic);catalogButton.Activated:Connect(function()task.spawn(catalog)end);prepareButton.Activated:Connect(prepare);Selection.SelectionChanged:Connect(updateSelection);widget:GetPropertyChangedSignal("Enabled"):Connect(function()toggle:SetActive(widget.Enabled)end);plugin.Unloading:Connect(function()alive=false end);task.spawn(function()while alive do if widget.Enabled then refresh()end;task.wait(POLL_SECONDS)end end)
